include:
  - component: $CI_SERVER_FQDN/components/sast/sast@3.4.0
  - component: $CI_SERVER_FQDN/components/dependency-scanning/main@1.1.1
  - component: $CI_SERVER_FQDN/components/secret-detection/secret-detection@2.3.0

stages:
  - release
  - test
  - build
  - deploy

gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: "$(date '+%Y-%m-%d')"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+(\.\d+)*$/'
      when: on_success

next_js_build:
  stage: build
  image: node:22.2.0-alpine3.19
  script:
    - cd front-end
    - cp ../.env.example .env
    - sed -i 's|base_path=|base_path=/osm-wikidata-map-framework/|' .env
    - echo "Building the app"
    - npm clean-install
    - npm run build
  artifacts:
    when: on_success
    access: all
    paths:
      - front-end/out
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+(\.\d+)*$/'
      exists:
        - front-end/package.json
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - front-end/package.json
      when: on_success
    - exists:
        - front-end/package.json
      when: manual

pages:
  stage: deploy
  needs:
    - next_js_build
  script:
    - cp -r front-end/out public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
