
.gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: "$(date '+%Y-%m-%d')"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+(\.\d+)*$/'
      when: on_success

.sentry_release: # Required secrets: SENTRY_ORG, SENTRY_AUTH_TOKEN
  stage: release
  image: getsentry/sentry-cli:1
  variables:
    SENTRY_LOG_LEVEL: debug
  script:
    - sentry-cli releases new --project "$SENTRY_PROJECT_NAME" "$SENTRY_RELEASE_NAME"
    - sentry-cli releases set-commits --auto "$SENTRY_RELEASE_NAME"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+(\.\d+)*$/'
      when: on_success

.sentry_deploy: # Required secrets: SENTRY_ORG, SENTRY_AUTH_TOKEN
  stage: deploy
  image: getsentry/sentry-cli:1
  variables:
    SENTRY_LOG_LEVEL: debug
  script:
    - sentry-cli releases deploys "$SENTRY_RELEASE_NAME" new -e "$DEPLOY_ENV_NAME"
    - if [ "prod" = $DEPLOY_ENV_NAME ]; then sentry-cli releases finalize "$SENTRY_RELEASE_NAME"; fi
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+(\.\d+)*$/'
      when: on_success
