# https://docs.docker.com/language/nodejs/build-images/
FROM node:20.5.0-alpine
WORKDIR /npm_app
COPY ["./package.json", "./package-lock.json", "./tsconfig.json", "./webpack.load-related.js", "/npm_app/"]
COPY "./src" "/npm_app/src"
RUN npm install && \
	npm run build-load-related && \
	mv /npm_app/public/dist/load-related/main.js /load-related.js && \
	rm -rf /npm_app/*
CMD ["node", "/load-related.js"]
