# baseUrl: http://localhost / https://etymology.dsantini.it

# New York
# https://etymology.dsantini.it/#-74.027,40.7306,9
GET {{baseUrl}}/elements.php
    ?from=bbox
    &minLat=40.229
    &minLon=-75.345
    &maxLat=41.229
    &maxLon=-72.709
    &language=it-IT
    &format=geojson
    &onlyCenter=true

#####

# San Jose / San Francisco
# https://etymology.dsantini.it/#-122.138,37.612,9
GET {{baseUrl}}/elements.php
    ?from=bbox
    &minLat=37.087
    &minLon=-123.456
    &maxLat=38.133
    &maxLon=-120.82
    &language=it-IT
    &format=geojson
    &onlyCenter=true

#####

# Berlin
# https://etymology.dsantini.it/#13.4247,52.5072,9
GET {{baseUrl}}/elements.php
    ?from=bbox
    &minLat=52.104
    &minLon=12.106
    &maxLat=52.907
    &maxLon=14.743
    &language=it-IT
    &format=geojson
    &onlyCenter=true

#####

# Dortmund / Dusserdorf / Cologne
# https://etymology.dsantini.it/#7.1627,51.2419,9
GET {{baseUrl}}/elements.php
    ?from=bbox
    &minLat=50.827
    &minLon=5.844
    &maxLat=51.653
    &maxLon=8.481
    &language=en-EN
    &format=geojson
    &onlyCenter=true

#####

# Brussels / Antwerp / Ghent
# http://etymology.dsantini.it/#4.0418,51.0282,9
GET {{baseUrl}}/elements.php
    ?from=bbox
    &minLat=50.705
    &minLon=2.987
    &maxLat=51.349
    &maxLon=5.096
    &language=en-EN
    &format=geojson
    &onlyCenter=true