# https://docs.docker.com/language/nodejs/build-images/
FROM node:23.11.0-alpine3.20
WORKDIR /npm_app

COPY ["package.json", "package-lock.json", "/npm_app/"]
RUN npm clean-install

COPY "src" "/npm_app/src"
COPY ["tsconfig.json", "declarations.d.ts", "/npm_app/"]
RUN npm run build-load-related

CMD ["npm", "run", "load-related"]
