apiVersion: v1
kind: Service
metadata:
  name: owmf-web-http-service
  labels:
    app: owmf-web
spec:
  type: NodePort
  selector:
    app: owmf-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
