# https://www.sumologic.com/blog/kubernetes-deploy-postgres/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owmf-db-volume-claim
  labels:
    app: owmf-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
