apiVersion: v1
kind: Service
metadata:
  name: owmf-web-https-service
  labels:
    app: owmf-web
spec:
  type: NodePort
  selector:
    app: owmf-web
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
