apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owmf-db
  labels:
    app: owmf-db
spec:
  selector:
    matchLabels:
      app: owmf-db
  serviceName: owmf-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: owmf-db
    spec:
      containers:
      - name: owmf-db
        #image: postgis/postgis:13-3.2-alpine #arm64 currently not supported, TODO check https://github.com/postgis/docker-postgis/issues/216
        image: odidev/postgis:13-3.1-alpine
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: owmf-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: owmf-db-data
          persistentVolumeClaim:
            claimName: owmf-db-volume-claim
