PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX ogc: <http://www.opengis.net/rdf#>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX osmrel: <https://www.openstreetmap.org/relation/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
    ?item
    ?osm
    ?etymology
    # (SAMPLE(COALESCE(?osm_lang_name,?wd_lang_label,?osm_default_name,?wd_default_label)) AS ?itemLabel)
    (SAMPLE(COALESCE(?osm_lang_name,?osm_default_name)) AS ?itemLabel)
    # (SAMPLE(COALESCE(?osm_descr,?wd_descr)) AS ?itemDescription)
    (SAMPLE(?osm_descr) AS ?itemDescription)
    #(SAMPLE(?_commons) AS ?commons)
    (SAMPLE(?_wikipedia) AS ?wikipedia)
    #(SAMPLE(?_picture) AS ?picture)
    (SAMPLE(?_wikimedia_commons) AS ?wikimedia_commons)
    (SAMPLE(?_image) AS ?image)
    (SAMPLE(?_height) AS ?height)
    (SAMPLE(?_levels) AS ?levels)
    (SAMPLE(?_building) AS ?building)
    (true AS ?from_osm) # TODO check if bound - https://github.com/ad-freiburg/qlever/wiki/Current-deviations-from-the-SPARQL-1.1-standard#sparql-11-features-that-are-not-yet-implemented-but-have-an-easy-workaround 
    (true AS ?from_wikidata)
    #(SAMPLE(?_statementEntity) AS ?statementEntity)
    (SAMPLE(?osm_location) AS ?location)
WHERE {
    SERVICE <https://qlever.cs.uni-freiburg.de/api/wikidata> {
        # VALUES (?_from_p ?_from_ps) { ${directPropertyValues} } # TODO Use VALUES when supported by QLever
        # ?item p:P625 ?locationStatement;
        #       ?_from_p ?stmt.
        ?item p:P625 ?locationStatement;
            p:${directProperty} ?stmt.

        ${wikidataCountryQuery}
        MINUS { ?item (wdt:P582|wdt:P585|wdt:P576|wdt:P3999|wdt:P376) ?_itemEndDate. } # Ignore if the feature has an end date or isn't on Earth # TODO Use blank nodes
        MINUS { ?locationStatement pq:P582 ?_locationEndDate. } # Ignore if the location statement has an end date # TODO Use blank nodes
        MINUS { ?stmt wikibase:rank wikibase:DeprecatedRank. }
        ?locationStatement ps:P625 ?wd_location.

        # # Filter by location (geo:sfWithin)
        # BIND ("POLYGON((${westLon} ${southLat}, ${westLon} ${northLat}, ${eastLon} ${northLat}, ${eastLon} ${southLat}, ${westLon} ${southLat}))"^^geo:wktLiteral AS ?bbox)
        # ?wd_location geo:sfWithin ?bbox.
        
        # # Filter by location (geof:latitude/longitude)
        BIND(geof:latitude(?wd_location) AS ?lat)
        BIND(geof:longitude(?wd_location) AS ?lon)
        FILTER (?lat > ${southLat})
        FILTER (?lat < ${northLat})
        FILTER (?lon > ${westLon})
        FILTER (?lon < ${eastLon})
        
        # # Filter by location (geof:distance)
        # BIND ("POINT(${centerLon} ${centerLat})"^^geo:wktLiteral AS ?center)
        # FILTER (geof:distance(?wd_location, ?center) <= ${maxDistanceKm})

        # ?stmt ?_from_ps ?etymology. # TODO Use VALUES when supported by QLever
        ?stmt ps:${directProperty} ?etymology.

        # # Extra details
        # TODO: QLever currently doesn't support OPTIONAL inside SERVICE
        # OPTIONAL { ?item @${language}@rdfs:label ?wd_lang_label. }
        # OPTIONAL { ?item @en@rdfs:label ?wd_default_label. }
        # OPTIONAL { ?item @${language}@schema:description ?wd_descr. }
        # OPTIONAL { ?item wdt:P910?/wdt:P373 ?_commons. }
        # OPTIONAL { ?_wikipedia schema:about ?item; schema:isPartOf <https://${language}.wikipedia.org/>. }
        # OPTIONAL { ?item wdt:P18 ?_picture. }
        # OPTIONAL { ?stmt pq:P805 ?_statementEntity. }
    }

    ?osm osm:wikidata ?item; geo:hasGeometry/geo:asWKT ?osm_location.
    # TODO: ?osm osm:wikidata/owl:sameAs? ?item
    # TODO: make the link optional and filter ?item is bound (BOUND() is not yet implemented in QLever)
    OPTIONAL { ?osm <https://www.openstreetmap.org/wiki/Key:name:${language}> ?osm_lang_name. }
    OPTIONAL { ?osm osmkey:name ?osm_default_name. }
    OPTIONAL { ?osm osmkey:description ?osm_descr. }
	OPTIONAL { ?osm osmkey:wikipedia ?_wikipedia }
    OPTIONAL { ?osm osmkey:wikimedia_commons ?_wikimedia_commons. }
    OPTIONAL { ?osm osmkey:image ?_image. }
    OPTIONAL { ?osm osmkey:height ?_height. }
    OPTIONAL { ?osm osmkey:building:levels ?_levels. }
    OPTIONAL { ?osm osmkey:building ?_building. }
}
GROUP BY ?item ?osm ?etymology
${limit}
