{
 "title": "Logs",
 "tags": [
  "open-etymology-map-detail",
  "open-etymology-map",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Apache access logs",
   "type": "logs",
   "description": "Excluding self & monitoring agent",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\",stream=\"stdout\",container_name=~\".*prod.*\"} !~ \".*(synthetic-monitoring-agent|127.0.0.1).*\" | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "Apache error logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\",stream=\"stderr\",container_name=~\".*prod.*\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "Host logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\",container_name=~\".*oem-postgis.*\"} | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}