{
 "title": "Statistics",
 "tags": [
  "open-etymology-map-detail",
  "open-etymology-map"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "type": "dashlist", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Requests by culture ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(8, sum by(code) (count_over_time({stream=\"stdout\", container_name=~\".*prod.*\"} | json line=\"log\" | line_format `{{.line}}` |~ `.*lang.*` | regexp `.*lang(uage)?=(?P<code>\\w{2}(?:-\\w{2})?)` [$__range])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Sites",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(site) (count_over_time({stream=\"stdout\", container_name=~\".*prod.*\"} |= `HTTP` != ` \"-\" ` != ` \\\"-\\\" ` | json line=\"log\" | line_format `{{.line}}` | regexp `\\d+ \\d+ \\\\?\"(?:https?://)?(?P<site>[\\w-]+\\.dsantini\\.it)(?:/[\\w\\?\\=\\-]*)?\\\\?\" ` [$__range]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "timeseries",
   "description": "https://grafana.com/blog/2022/01/11/top-5-user-requested-synthetic-monitoring-alerts-in-grafana-cloud/",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\nsum by (job) (rate(probe_all_success_sum{job=~\"open-.+-map-.+\"}[$__rate_interval]))\r\n/\r\nsum by (job) (rate(probe_all_success_count{job=~\"open-.+-map-.+\"}[$__rate_interval]))\r\n)"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(probe_all_success_sum{job=~\"open-etymology-map.*\"}[$__range])\r\n) / sum(\r\n  increase(probe_all_success_count{job=~\"open-etymology-map.*\"}[$__range])\r\n)"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry{job=~\"open-etymology-map.*\"}) - time()"
    }
   ]
  },
  {
   "title": "Requests by culture",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate({stream=\"stdout\", container_name=~\".*prod.*\"} | json line=\"log\" | line_format `{{.line}}` |~ `.*lang.*` | regexp `.*lang(uage)?=(?P<code>\\w{2,3}(?:-\\w{2})?)` [$__interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests by response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate({stream=\"stdout\", container_name=~\".*prod.*\"} | json line=\"log\" | line_format \"{{.line}}\" | pattern `<_> <_> - - <_> <_> <_> <_> <_> <code> <_> <_> <_> <_>` [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests by source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate({stream=\"stdout\", container_name=~\".*prod.*\"} | json line=\"log\" | line_format `{{.line}}` |~ `.*source.*` | regexp `.*source?=(?P<code>\\w+)` [$__interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{job=~\"open-etymology-map.*\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Requests by client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate({stream=\"stdout\", container_name=~\".*prod.*\"}  |~ \".*synthetic-monitoring-agent.*\" [$__interval]))",
     "legendFormat": "Synthetic monitoring agent"
    },
    {
     "expr": "sum (rate({stream=\"stdout\", container_name=~\".*prod.*\"}  !~ \".*(127.0.0.1|synthetic-monitoring-agent).*\" [$__interval]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Logs by source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate({job=\"varlogs\"} [$__interval])",
     "legendFormat": "{{filename}}"
    },
    {
     "expr": "sum by (container_name) (rate({job=\"containerlogs\", container_name=~\".+\"} [$__interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}