#defaultView:BarChart
SELECT
    ?name
    (COUNT(DISTINCT ?wikidata) AS ?count)
    ?id
    (SAMPLE(?superClassID) AS ?class)
    (GROUP_CONCAT(DISTINCT STRAFTER(STR(?wikidata),STR(wd:));separator=',') AS ?subjects)
WHERE {
    VALUES ?wikidata { ${wikidataValues} }

    # industry - https://www.wikidata.org/wiki/Property:P452
    # field of work - https://www.wikidata.org/wiki/Property:P101
    ?wikidata wdt:P452|wdt:P101 ?id.
    ?id rdfs:label ?name FILTER(lang(?name)='${language}').

    OPTIONAL { ?id wdt:P279 ?superClassID. }
}
GROUP BY ?name ?id
ORDER BY DESC(?count)
LIMIT 100