#defaultView:BarChart
SELECT
    ?name
    (COUNT(DISTINCT ?wikidata) AS ?count)
    ?id
    (SAMPLE(?superClassID) AS ?class)
    (GROUP_CONCAT(DISTINCT STRAFTER(STR(?wikidata),STR(wd:));separator=',') AS ?subjects)
WHERE {
    VALUES ?wikidata { ${wikidataValues} }

    ?wikidata wdt:P106|wdt:P3989 ?id.
    ?id rdfs:label ?name FILTER(lang(?name)='${language}').

    OPTIONAL { ?id wdt:P279 ?superClassID. }
}
GROUP BY ?name ?id
ORDER BY DESC(?count)
LIMIT 100