@startuml v1

actor user as "User"
frame owmf as "OSM-Wikidata Map Framework v1" {
    node "Front-end" {
        component index as "index.php"
    }
    node "Back-end" {
        component etymologyMap as "etymologyMap.php"
        component elements as "elements.php"
        component stats as "stats.php"
        package "App\Query\Combined" {
            card BBoxGeoJSONEtymologyQuery
            card BBoxStatsOverpassWikidataQuery
            card BBoxJSONOverpassWikidataQuery
        }
        package "App\Query\Wikidata" {
            card BaseWikidataQuery
            card EtymologyIDListXMLWikidataQuery
            card TypeStatsWikidataQuery
            card GenderStatsWikidataQuery
        }
        package "App\Query\Overpass" {
            card BaseOverpassQuery
            card BBoxEtymologyOverpassQuery
            card BBoxEtymologyCenterOverpassQuery
        }
/'
        package "App\Query\Caching" {
            card CSVCachedBBoxGeoJSONQuery
            card CSVCachedBBoxJSONQuery
        }
        'file cache as "Cache"
'/
    }
}
agent wikidata as "Wikidata SPARQL API"
agent overpass as "Overpass API"

user --> index
index -(0- etymologyMap
index -(0- elements
index -(0- stats

/'
stats  ..> CSVCachedBBoxJSONQuery
etymologyMap  ..> CSVCachedBBoxGeoJSONQuery
elements ..> CSVCachedBBoxGeoJSONQuery
CSVCachedBBoxGeoJSONQuery --|> CSVCachedBBoxJSONQuery
CSVCachedBBoxJSONQuery --> cache
'/

elements --> BBoxEtymologyCenterOverpassQuery
etymologyMap --> BBoxGeoJSONEtymologyQuery
stats --> BBoxStatsOverpassWikidataQuery

BBoxGeoJSONEtymologyQuery --|> BBoxJSONOverpassWikidataQuery
BBoxStatsOverpassWikidataQuery --|> BBoxJSONOverpassWikidataQuery

BBoxEtymologyOverpassQuery --|> BaseOverpassQuery
BBoxEtymologyCenterOverpassQuery --|> BaseOverpassQuery

EtymologyIDListXMLWikidataQuery --|> BaseWikidataQuery
TypeStatsWikidataQuery --|> BaseWikidataQuery
GenderStatsWikidataQuery --|> BaseWikidataQuery

BBoxJSONOverpassWikidataQuery --> BBoxEtymologyOverpassQuery
BBoxGeoJSONEtymologyQuery --> EtymologyIDListXMLWikidataQuery
BBoxStatsOverpassWikidataQuery --> GenderStatsWikidataQuery
BBoxStatsOverpassWikidataQuery --> TypeStatsWikidataQuery

BaseOverpassQuery --(0- overpass
BaseWikidataQuery --(0- wikidata

@enduml