@startuml db-init

card "Get config and parameters" as param #LightGreen
cloud "OSM extract mirror" as mirror
file X.osm.pbf
card Download #LightYellow
mirror <.> Download
param -[bold]-> Download
Download .> X.osm.pbf

note as xsize
  Size: 50MB ~ 70GB
end note
X.osm.pbf .. xsize

card "osmium tags-filter" as filter1 #LightGreen
file with_name.osm.pbf as file1
X.osm.pbf .> filter1
Download -[bold]-> filter1
filter1 .> file1

card "osmium tags-filter" as filter2 #LightGreen
file possible_etymology.osm.pbf as file2
file1 .> filter2
filter1 -[bold]-> filter2
filter2 .> file2

card "osmium tags-filter" as filter3 #LightGreen
file filtered.osm.pbf as file3
file2 .> filter3
filter2 -[bold]-> filter3
filter3 .> file3

note as 3size
  Size: 4MB ~ 6GB
end note
3size .. file3

card "osmium export" as export #LightGreen
file X.osm.pbf.pg as tsv
file3 .> export
filter3 -[bold]-> export
export .> tsv

note as tsvsize
  Size: 40MB ~ 22GB
end note
tsvsize .. tsv

database "Local DB" as db #LightBlue
card "Setup DB schema" as setup #LightGreen
setup .left.> db #Blue
export -[bold]-> setup

card "pgSQL COPY FROM CSV" as copy #LightGreen
tsv .> copy
setup -[bold]-> copy
copy .left.> db #Blue

card "Remove elements too big" as toobig #LightGreen
toobig <.left.> db #Blue
copy -[bold]-> toobig

card "Convert element wikidata codes" as wdcod #LightGreen
wdcod <.left.> db #Blue
toobig -[bold]-> wdcod

card "Load and convert wikidata entities" as wdent #LightGreen
file "wikidata-init.csv" as csv
csv .> wdent
wdent <.left.> db #Blue
wdcod -[bold]-> wdent

card "Load wikidata 'consists of' entities" as wdcoent #LightGreen
cloud "Wikidata Query Service" as wd
wd <.> wdcoent
wdcoent <.left.> db #Blue
wdent -[bold]-> wdcoent

card "Propagate etymologies" as propagate #LightGreen
propagate <.left.> db #Blue
wdcoent -[bold]-> propagate

card "Load wikidata 'named after' entities" as wdnaent #LightGreen
wd <.> wdnaent
wdnaent <.left.> db #Blue
propagate -[bold]-> wdnaent

card "Convert etymologies" as ety #LightGreen
ety <.left.> db #Blue
wdnaent -[bold]-> ety

card "Remove elements without etymology" as temp #LightGreen
temp <.left.> db #Blue
ety -[bold]-> temp

card "Setup global map" as global #LightGreen
global <.left.> db #Blue
temp -[bold]-> global

card "Save update date" as date #LightGreen
date <.left.> db #Blue
global -[bold]-> date

file X.osm.pbf.backup as backup
card pg_dump #LightGreen
db .> pg_dump #Blue
pg_dump .> backup
date -[bold]-> pg_dump

note as busize
  Size: 70KB ~ 170MB
end note
busize .. backup

database "Destination DB" as destdb #LightCoral
card pg_restore #LightYellow
backup .> pg_restore
pg_restore .> destdb #Coral
pg_dump -[bold]-> pg_restore

@enduml