@startuml dev_deployment

actor Browser
rectangle "Docker Compose --profile 'dev'" as docker {
  port "8000" as 8000docker
  port "5432" as 5432docker
  port "80" as 80docker
  node "oem-postgis" {
    port 5432 as 5432db
    database "PostGIS DB" as db
  }
  node pgadmin {
    port "80" as 80pgAdmin
    component pgAdmin
  }
  node "oem-web-dev" {
    port "80" as 80webDev
    component Apache
    folder "/var/www/app" as appRem
    folder "/var/www/html" as htmlRem
  }

}
folder "public" as htmlLoc
folder "app" as appLoc

Apache --> 5432db
pgAdmin --> 5432db

Browser --> 80docker
Browser --> 8000docker

80docker --> 80webDev
8000docker --> 80pgAdmin
5432docker --> 5432db

htmlLoc ... htmlRem : volume
appLoc ... appRem : volume

80webDev -> Apache
5432db -> db
80pgAdmin -> pgAdmin

@enduml
