@startuml prod+db_deployment

actor Browser
component Server {
  port "80" as 80docker
  rectangle "Docker Compose --profile 'prod+db'" as docker {
    node "oem-postgis" {
      port 5432 as 5432db
      database "PostGIS DB" as db
    }
    node "oem-web-prod" {
      port "80" as 80webProd
      component Apache
    }
  }
}

Apache --> 5432db

Browser --> 80docker

80docker --> 80webProd

80webProd --> Apache
5432db --> db

@enduml
