@startuml prod_deployment

actor Browser
component Server {
  port "80" as 80docker
  rectangle "Docker Compose --profile 'prod'" as docker {
    node "oem-web-prod" {
      port "80" as 80webProd
      component Apache
    }
  }
}
cloud {
  database "PostGIS DB or Overpass API" as db
}

Apache ---> db

Browser --> 80docker

80docker --> 80webProd

80webProd --> Apache

@enduml
