#defaultView:BarChart
SELECT
    (?id AS ?name)
    (COUNT(DISTINCT ?wikidata) AS ?count)
    ?id
    (GROUP_CONCAT(DISTINCT STRAFTER(STR(?wikidata),STR(wd:));separator=',') AS ?subjects)
WHERE {
    VALUES ?wikidata { ${wikidataValues} }

    OPTIONAL { ?wikidata wdt:P18|wdt:P94|wdt:P242|wdt:P15|wdt:P41 ?picture. }
    BIND(IF(BOUND(?picture), 'available', 'unavailable') AS ?id)
}
GROUP BY ?id