#defaultView:Map
SELECT
    ?item
    (SAMPLE(COALESCE(?langLabel,?defaultLabel,?anyLabel)) AS ?itemLabel)
    (SAMPLE(?_itemDescription) AS ?itemDescription)
    (SAMPLE(?_location) AS ?location)
    (SAMPLE(?_commons) AS ?commons)
    (SAMPLE(?_wikipedia) AS ?wikipedia)
    (SAMPLE(?_picture) AS ?picture)
    (SAMPLE(?_osm_node) AS ?osm_node)
    (SAMPLE(?_osm_way) AS ?osm_way)
    (SAMPLE(?_osm_rel) AS ?osm_rel)
    (SAMPLE(?_alias) AS ?alias)
    ?etymology
    (?item AS ?from_entity)
    (SAMPLE(?_from_prop) AS ?from_prop)
WHERE {
    VALUES ?_from_prop { ${directProperties} }
    ?item p:P625 ?locationStatement;
          ?_from_prop ?etymology;
          rdfs:label ?anyLabel.
    FILTER (isIRI(?etymology) && !wikibase:isSomeValue(?etymology))
    MINUS { ?item (wdt:P582|wdt:P585|wdt:P576|wdt:P3999) []. } # Ignore if the feature has an end date
    MINUS { ?locationStatement pq:P582 []. } # Ignore if the location statement has an end date

    # Filter by location
    SERVICE wikibase:box {
        ?locationStatement ps:P625 ?_location.
        bd:serviceParam wikibase:cornerWest 'POINT(${southLon} ${westLat})'^^geo:wktLiteral;
                        wikibase:cornerEast 'POINT(${northLon} ${eastLat})'^^geo:wktLiteral.
    } # https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Search_within_box
    
    OPTIONAL { ?item rdfs:label ?langLabel FILTER(LANG(?langLabel) = '${language}'). }
    OPTIONAL { ?item rdfs:label ?defaultLabel FILTER(LANG(?defaultLabel) = '${defaultLanguage}'). }
    OPTIONAL { ?item schema:description ?_itemDescription FILTER(LANG(?_itemDescription) = '${language}'). }
    OPTIONAL { ?item wdt:P373 ?_commons. }
    OPTIONAL { ?_wikipedia schema:about ?item; schema:isPartOf <https://${language}.wikipedia.org/>. }
    OPTIONAL { ?item wdt:P18 ?_picture. }
    OPTIONAL { ?item wdt:P11693 ?_osm_node. }
    OPTIONAL { ?item wdt:P10689 ?_osm_way. }
    OPTIONAL { ?item wdt:P402 ?_osm_rel. }
    OPTIONAL { ?_alias owl:sameAs ?item. }
}
GROUP BY ?item ?etymology
${limit}
