PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX osmrel: <https://www.openstreetmap.org/relation/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX ogc: <http://www.opengis.net/rdf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT
    ?item
    ?osm
    ?location
    ?etymology
    ${osmTextSelect}
    ${osmDescriptionSelect}
    (COALESCE(?osm_lang_name,?osm_default_name) AS ?itemLabel)
    (?osm_descr AS ?itemDescription)
    ?image
    ?wikimedia_commons
    (true AS ?from_osm)
    (false AS ?from_wikidata)
WHERE {
    ${osmEtymologyExpression}
    ${osmCountryQuery}
    ?osm geo:hasGeometry ?location.

    # # Filter by location (geo:sfWithin)
    # BIND ("POLYGON((${westLon} ${southLat}, ${westLon} ${northLat}, ${eastLon} ${northLat}, ${eastLon} ${southLat}, ${westLon} ${southLat}))"^^geo:wktLiteral AS ?bbox)
    # ?location geo:sfWithin ?bbox.
    
    # # Filter by location (geof:latitude/longitude)
    BIND(geof:latitude(?location) AS ?lat)
    BIND(geof:longitude(?location) AS ?lon)
    FILTER (?lat > ${southLat} && ?lat < ${northLat} && ?lon > ${westLon} && ?lon < ${eastLon})
    
    # # Filter by location (geof:distance)
    # BIND ("POINT(${centerLon} ${centerLat})"^^geo:wktLiteral AS ?center)
    # FILTER (geof:distance(?location, ?center) <= ${maxDistanceKm})

    # # Extra details
    OPTIONAL { ?osm osm:wikidata ?item. }
    OPTIONAL { ?osm <https://www.openstreetmap.org/wiki/Key:name:${language}> ?osm_lang_name. }
    OPTIONAL { ?osm osmkey:name ?osm_default_name. }
    OPTIONAL { ?osm osmkey:description ?osm_descr. }
    OPTIONAL { ?osm osmkey:image ?image. }
    OPTIONAL { ?osm osmkey:wikimedia_commons ?wikimedia_commons. }
}