PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
SELECT DISTINCT
    ?etymology
    ?location
    ?commons
    ?picture
    ?osm_node
    ?osm_way
    ?osm_rel
    (?etymology AS ?from_entity)
    (wdt:${indirectProperty} AS ?from_prop)
    (false AS ?from_osm)
    (true AS ?from_wikidata)
WHERE {
    ?etymology p:${indirectProperty} ?stmt.
    MINUS { ?stmt pq:P582 []. } # Ignore if the etymology statement has an end date
    
    # Filter by location
    ?stmt pq:P625 ?location.
    # ?location geo:sfWithin "POLYGON((${westLon} ${southLat}, ${westLon} ${northLat}, ${eastLon} ${northLat}, ${eastLon} ${southLat}, ${westLon} ${southLat}))"^^geo:wktLiteral.
    BIND ("POINT(${centerLon} ${centerLat})"^^geo:wktLiteral AS ?center)
    FILTER (geof:distance(?location, ?center) <= ${maxDistanceKm})
    
    OPTIONAL { ?stmt pq:P373 ?commons. }
    ${pictureQuery}
    OPTIONAL { ?stmt pq:P11693 ?osm_node. }
    OPTIONAL { ?stmt pq:P10689 ?osm_way. }
    OPTIONAL { ?stmt pq:P402 ?osm_rel. }
}
${limit}
