#defaultView:BarChart
SELECT
    ?name
    (COUNT(DISTINCT ?wikidata) AS ?count)
    (STRAFTER(STR(?id),STR(wd:)) AS ?id)
    (GROUP_CONCAT(DISTINCT STRAFTER(STR(?wikidata),STR(wd:));separator=',') AS ?subjects)
WHERE {
    VALUES ?wikidata { ${wikidataValues} }

    ?id ^wdt:P17|^wdt:P27 ?wikidata;
        rdfs:label ?name FILTER(lang(?name)='${language}').
}
GROUP BY ?name ?id
ORDER BY DESC(?count)
LIMIT 50