SELECT ?wikidata
    (SAMPLE(?instanceID) AS ?instanceID)
    (SAMPLE(?genderID) AS ?genderID)
    (SAMPLE(?commons) AS ?commons)
    (GROUP_CONCAT(DISTINCT ?picture; SEPARATOR='`') AS ?pictures)
    (SAMPLE(?event_date) AS ?event_date)
    (SAMPLE(?event_date_precision) AS ?event_date_precision)
    (SAMPLE(?start_date) AS ?start_date)
    (SAMPLE(?start_date_precision) AS ?start_date_precision)
    (SAMPLE(?end_date) AS ?end_date)
    (SAMPLE(?end_date_precision) AS ?end_date_precision)
    (SAMPLE(?birth_date) AS ?birth_date)
    (SAMPLE(?birth_date_precision) AS ?birth_date_precision)
    (SAMPLE(?death_date) AS ?death_date)
    (SAMPLE(?death_date_precision) AS ?death_date_precision)
    (SAMPLE(?wkt_coords) AS ?wkt_coords)
WHERE {
    VALUES ?wikidata { __WIKIDATA_IDS__ }

    {
        ?instanceID ^wdt:P31 ?wikidata.
    } UNION {
        ?instanceID ^wdt:P279 ?wikidata.
    }

    OPTIONAL {
        {
            ?picture ^wdt:P18 ?wikidata # picture
        } UNION {
            ?picture ^wdt:P94 ?wikidata # coat of arms image
        }
    }

    OPTIONAL {
        ?genderID ^wdt:P21 ?wikidata.
    }

    OPTIONAL {
        ?wikidata p:P585/psv:P585 [
            wikibase:timePrecision ?event_date_precision;
            wikibase:timeValue ?event_date
        ].
        MINUS {
            ?wikidata p:P585/psv:P585/wikibase:timePrecision ?other_event_date_precision.
            FILTER (?other_event_date_precision > ?event_date_precision).
        }.
    }

    OPTIONAL {
        ?wikidata p:P580/psv:P580 [
            wikibase:timePrecision ?start_date_precision;
            wikibase:timeValue ?start_date
        ].
        MINUS {
            ?wikidata p:P585/psv:P585/wikibase:timePrecision ?other_start_date_precision.
            FILTER (?other_start_date_precision > ?start_date_precision).
        }.
    }

    OPTIONAL {
        ?wikidata p:P582/psv:P582 [
            wikibase:timePrecision ?end_date_precision;
            wikibase:timeValue ?end_date
        ].
        MINUS {
            ?wikidata p:P585/psv:P585/wikibase:timePrecision ?other_end_date_precision.
            FILTER (?other_end_date_precision > ?end_date_precision).
        }.
    }

    OPTIONAL {
        ?wikidata p:P569/psv:P569 [
            wikibase:timePrecision ?birth_date_precision;
            wikibase:timeValue ?birth_date
        ].
        MINUS {
            ?wikidata p:P585/psv:P585/wikibase:timePrecision ?other_birth_date_precision.
            FILTER (?other_birth_date_precision > ?birth_date_precision).
        }.
    }

    OPTIONAL {
        ?wikidata p:P570/psv:P570 [
            wikibase:timePrecision ?death_date_precision;
            wikibase:timeValue ?death_date
        ].
        MINUS {
            ?wikidata p:P585/psv:P585/wikibase:timePrecision ?other_death_date_precision.
            FILTER (?other_death_date_precision > ?death_date_precision).
        }.
    }

    OPTIONAL {
        ?commons ^wdt:P373 ?wikidata.
    }

    OPTIONAL {
        ?wkt_coords ^wdt:P625 ?wikidata.
        FILTER(STRSTARTS(?wkt_coords, 'Point')).
    }
}
GROUP BY ?wikidata