services:  
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.13
    ports:
      - "${owmf_swagger_port:-8080}:8080"
    volumes:
      - ./commons.yaml:/usr/share/nginx/html/commons.yaml
      - ./sparql.yaml:/usr/share/nginx/html/sparql.yaml
    environment:
      - API_URL=wikibase.json
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/"]
      interval: 20s
      timeout: 1s
      retries: 5
    restart: unless-stopped
