#defaultView:BarChart
SELECT ?name (COUNT(DISTINCT ?wikidata) AS ?count) ?id (GROUP_CONCAT(DISTINCT REPLACE(STR(?wikidata),STR(wd:),'');separator=',') AS ?items)
WHERE {
    VALUES ?wikidata { ${wikidataValues} }

    ?id ^wdt:P31|^wdt:P279 ?wikidata;
        rdfs:label ?name FILTER(lang(?name)='${language}').
}
GROUP BY ?name ?id
ORDER BY DESC(?count)
LIMIT 30