CREATE EXTENSION IF NOT EXISTS postgis;

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;

CREATE EXTENSION IF NOT EXISTS postgis_topology;

CREATE EXTENSION IF NOT EXISTS hstore;

--CREATE EXTENSION IF NOT EXISTS unaccent;

SELECT PostGIS_Version();
